# Generated by Django 4.1.13 on 2024-12-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='properties',
            field=models.JSONField(default=list),
        ),
    ]
