# Generated by Django 4.1.13 on 2024-12-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_task_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
    ]
