# Generated by Django 4.1.13 on 2024-12-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='object',
            field=models.CharField(blank=True, choices=[('class', 'Class'), ('assignment', 'Assignment'), ('exam', 'Exam')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='properties',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
