# Generated by Django 4.1.13 on 2024-12-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_task_object_alter_task_properties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='properties',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
